name: Deploy Node.js React App and Strapi to Oracle Cloud VM

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.0

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Specify the Node.js version

      # Use the webfactory/ssh-agent action to add the SSH key
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Install dependencies and build React app
      - name: Install React dependencies and build
        run: |
          cd react/react-app  # Navigate to your React app directory
          npm install  # Install dependencies
          npm run build  # Build the React app

      # Install dependencies and build Strapi
      - name: Install Strapi dependencies
        run: |
          cd strapi/strapi-app  # Navigate to your Strapi app directory
          npm install  # Install Strapi dependencies
          npm run build  # Build Strapi

      # Deploy React and Strapi to Oracle Cloud VM
      - name: Deploy React App to Oracle Cloud VM
        run: |
          # Create a single archive of the React build files
          tar -czf /tmp/react_build.tar.gz -C react/react-app/build .  # Archive the React build files
          
          # Copy the archive to the remote server
          scp -o StrictHostKeyChecking=no /tmp/react_build.tar.gz opc@${{ secrets.ORACLE_IP }}:/tmp/
          
          # SSH into the server, extract the files, and restart Nginx
          ssh opc@${{ secrets.ORACLE_IP }} 'sudo tar -xzf /tmp/react_build.tar.gz -C /usr/share/nginx/html/sif_coupons && sudo systemctl restart nginx'


      - name: Deploy Strapi to Oracle Cloud VM
        run: |
          # Create an archive of the Strapi build files
          tar -czf /tmp/strapi_build.tar.gz -C strapi/strapi-app .  # Archive the Strapi build files
      
          # Copy the archive to the remote server
          scp -o StrictHostKeyChecking=no /tmp/strapi_build.tar.gz opc@${{ secrets.ORACLE_IP }}:/tmp/
      
          # SSH into the server, extract the files, install production dependencies, and restart Strapi with pm2
          ssh opc@${{ secrets.ORACLE_IP }} 'sudo tar -xzf /tmp/strapi_build.tar.gz -C /var/www/sif_coupons && cd /var/www/sif_coupons && npm install --production && pm2 restart strapi'
